export const T = {
  vi: {
    appTitle: 'Báo giá',
    developedBy: 'Phát triển bởi: Tiền/Cảng Tân Thuận',
    manageTariff: 'Phương án (Tariff)',
    historyBtn: 'Lịch sử',
    switchLang: 'EN / VI',
    sectionInfo: 'Thông tin chung',
    labelQuoteNo: 'Số',
    labelDate: 'Ngày',
    labelCustomer: 'Tên khách hàng',
    labelTaxCode: 'Mã số thuế',
    labelAddress: 'Địa chỉ',
    labelPhone: 'Điện thoại',
    labelNotes: 'Ghi chú',
    thService: 'Phương án',
    thQty: 'Số lượng',
    thPrice: 'Đơn giá',
    thAmount: 'Thành tiền',
    addRow: '+ Thêm dòng',
    total: 'Tổng cộng:',
    inWords: 'Bằng chữ:',
    sectionActions: 'Xem trước',
    btnNew: 'Tạo mới',
    btnSave: 'Lưu',
    btnUpdate: 'Cập nhật',
    btnPdf: 'In / Xuất PDF',
    previewPlaceholder: 'Bản xem trước (A4)',
    selectService: '-- Chọn phương án --',
    otherService: 'Phương án khác',
    confirmNew: 'Tạo báo giá mới sẽ xóa toàn bộ thông tin hiện tại. Bạn có chắc chắn?',
    confirmDeleteQuote: 'Bạn có chắc muốn xóa báo giá này không?',
    dong: 'đồng',
    storageKw: 'lưu bãi',
    powerKw: 'chạy điện',
    containerQtyLbl: 'Số lượng cont:',
    dateFromLbl: 'Từ ngày:',
    dateToLbl: 'Đến ngày:',
    pdf: {
      company: 'TTĐH KHAI THÁC TÂN THUẬN',
      companyAddr: 'Địa chỉ: 18B Lưu Trọng Lư, Phường Tân Thuận, TP. HCM',
      phone: 'Điện thoại',
      title: 'BÁO GIÁ',
      vat: '(Đã bao gồm 8% thuế VAT)',
      thNo: 'STT', thService: 'Phương án', thUnit: 'DVT', thQty: 'SL', thPrice: 'Đơn giá', thAmount: 'Thành tiền',
      totalPayment: 'Tổng cộng tiền thanh toán:',
      inWords: 'Số tiền viết bằng chữ:',
      paymentInfo: 'THÔNG TIN THANH TOÁN',
      bank: 'Ngân hàng', accountName: 'Tên TK', accountNo: 'Số TK',
      noteTitle: 'Lưu ý:',
      notes: `<li style="margin-bottom:4px">Chúng tôi báo giá theo thông tin khách hàng cung cấp, vui lòng kiểm tra lại phương án.</li><li style="margin-bottom:4px">Đối với phương án đóng/rút/sang container, chúng tôi không chịu trách nhiệm việc tháo gỡ, chằng buộc hàng hoá, cũng như các hư hỏng bên trong container như xước, gãy ván sàn...</li><li>Nếu phát sinh thêm phương án, sẽ căn cứ vào thực tế hiện trường để thu phí bổ sung.</li>`
    }
  },
  en: {
    appTitle: 'Service Quotation',
    developedBy: 'Developed by: Tien/Tan Thuan Port',
    manageTariff: 'Manage Services (Tariff)',
    historyBtn: 'Quotation History',
    switchLang: 'VI / EN',
    sectionInfo: 'Informations',
    labelQuoteNo: 'Quotation No.',
    labelDate: 'Date',
    labelCustomer: 'Customer Name',
    labelTaxCode: 'Tax Code',
    labelAddress: 'Address',
    labelPhone: 'Phone',
    labelNotes: 'Notes',
    thService: 'Service',
    thQty: 'Qty',
    thPrice: 'Unit Price',
    thAmount: 'Amount',
    addRow: '+ Add Row',
    total: 'Total:',
    inWords: 'In words:',
    sectionActions: 'Preview',
    btnNew: 'New',
    btnSave: 'Save Quotation',
    btnUpdate: 'Update Preview',
    btnPdf: 'Print / Export PDF',
    previewPlaceholder: 'A4 Preview',
    selectService: '-- Select a service --',
    otherService: 'Other Service',
    confirmNew: 'This will clear all current quotation data. Are you sure?',
    confirmDeleteQuote: 'Are you sure you want to delete this quotation?',
    dong: 'Dong',
    storageKw: 'storage',
    powerKw: 'power supply',
    containerQtyLbl: 'Container qty:',
    dateFromLbl: 'From date:',
    dateToLbl: 'To date:',
    pdf: {
      company: 'TAN THUAN OPERATIONS CENTER',
      companyAddr: 'Address: 18B Luu Trong Lu, Tan Thuan Ward, Ho Chi Minh City',
      phone: 'Phone',
      title: 'QUOTATION',
      vat: '(Includes 8% VAT)',
      thNo: 'No.', thService: 'Service', thUnit: 'Unit', thQty: 'Qty', thPrice: 'Unit Price', thAmount: 'Amount',
      totalPayment: 'Total payment:',
      inWords: 'In words:',
      paymentInfo: 'PAYMENT INFORMATION',
      bank: 'Bank', accountName: 'Account Name', accountNo: 'Account Number',
      noteTitle: 'Notes:',
      notes: `<li style="margin-bottom:4px">This quotation is based on your information. Please double check.</li><li style="margin-bottom:4px">We are not responsible for damages inside containers.</li><li>Additional costs may apply.</li>`
    }
  }
} as const;

export type Lang = keyof typeof T;
export type TStrings = typeof T.vi;
